export const ActionTypes = {
    SET_PRODUCTS : 'SET_PRODUCTS',
    ADD_TO_CART : 'ADD_TO_CART',
    ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    REMOVE_FROM_WISHLIST: 'REMOVE_FROM_WISHLIST'
}